services:
    postgres:
        image: "bitnami/postgresql:latest"
        ports:
            - "5432:5432"
        environment:
            POSTGRESQL_USER: postgres
            POSTGRESQL_PASSWORD: postgres
            POSTGRESQL_DB: track-job
